services:
  - type: web
    name: puffingood-backend
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: CORS_ORIGIN
        value: https://puffingood.com
      - key: RATE_LIMIT_WINDOW
        value: 15
      - key: RATE_LIMIT_MAX_REQUESTS
        value: 100
